//
// ActivationAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class ActivationAPI {
    /**
     Status

     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func status1(completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        status1WithRequestBuilder().execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     Status
     - GET /activation/status
     - Get activation status

     - returns: RequestBuilder<Void> 
     */
    open class func status1WithRequestBuilder() -> RequestBuilder<Void> {
        let path = "/activation/status"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
