//
// LeasingAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class LeasingAPI {
    /**
     Get all active leases for an address
     - parameter address: (path) Wallet address  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func active1(address: String, completion: @escaping ((_ data: Function1RequestContextFutureRouteResult?,_ error: Error?) -> Void)) {
        active1WithRequestBuilder(address: address).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Get all active leases for an address
     - GET /leasing/active/{address}
     - parameter address: (path) Wallet address  

     - returns: RequestBuilder<Function1RequestContextFutureRouteResult> 
     */
    open class func active1WithRequestBuilder(address: String) -> RequestBuilder<Function1RequestContextFutureRouteResult> {
        var path = "/leasing/active/{address}"
        let addressPreEscape = "\(address)"
        let addressPostEscape = addressPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{address}", with: addressPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<Function1RequestContextFutureRouteResult>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
