//
// ConnectReq.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public struct ConnectReq: Codable {


    public var host: String

    public var port: Int
    public init(host: String, port: Int) { 
        self.host = host
        self.port = port
    }

}
