//
// DataEntryObject.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public struct DataEntryObject: Codable {

    public enum ModelType: String, Codable { 
        case integer = "integer"
        case boolean = "boolean"
        case binary = "binary"
        case string = "string"
    }    /** integer */
    public var type: ModelType

    public var key: String

    public var value: BigDecimal
    public init(type: ModelType, key: String, value: BigDecimal) { 
        self.type = type
        self.key = key
        self.value = value
    }

}
