//
// Function1RequestContextFutureRouteResult.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public struct Function1RequestContextFutureRouteResult: Codable {


}
